// src/ui/windows/Main.vue
<script lang="ts" setup>
import { watch, onMounted, ref } from "vue";
import { SearchResultItem, IPCEvent, Icon, IconType } from "../../common";
import SearchIcon from "../icons/SearchIcon.vue";
import RefreshingIcon from "../icons/RefreshingIcon.vue";

let results = ref<SearchResultItem[]>([]);
let currentQuery = ref("");
let currentSelection = ref(0);
let refreshingIndex = ref(false);

// handlers
function search(query: string) {
  if (query) {
    window.KAL.ipc.send(IPCEvent.Search, query);
  } else {
    results.value = [];
    window.KAL.ipc.send(IPCEvent.ClearResults);
  }
}

watch(currentQuery, (query) => search(query));

function onkeydown(e: KeyboardEvent) {
  if (e.key === "Escape") {
    e.preventDefault();
    window.KAL.ipc.send(IPCEvent.HideMainWindow);
  }

  if (["ArrowDown", "ArrowUp"].includes(e.key)) {
    e.preventDefault();
    if (e.key === "ArrowDown") {
      currentSelection.value =
        currentSelection.value === results.value.length - 1
          ? 0
          : currentSelection.value + 1;
    } else {
      currentSelection.value =
        currentSelection.value === 0
          ? results.value.length - 1
          : currentSelection.value - 1;
    }

    document
      .getElementById(`search-results_item_#${currentSelection}`)
      ?.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }

  if (e.key === "Enter") {
    e.preventDefault();
    window.KAL.ipc.send(IPCEvent.Execute, currentSelection.value, e.shiftKey);
  }

  if (e.ctrlKey && e.key === "o") {
    e.preventDefault();
    window.KAL.ipc.send(IPCEvent.OpenLocation, currentSelection.value);
  }

  if (e.ctrlKey && e.key === "r") {
    e.preventDefault();
    window.KAL.ipc.send(IPCEvent.RefreshIndex);
    refreshingIndex.value = true;
  }
}

onMounted(() => {
  window.KAL.ipc.on(IPCEvent.FocusInput, () => {
    let input = document.getElementById("search-input");
    input?.focus();
    (input as HTMLInputElement).select();
  });

  window.KAL.ipc.on(IPCEvent.Results, (payload: SearchResultItem[]) => {
    currentSelection.value = 0;
    results.value = payload;
  });

  window.KAL.ipc.on(IPCEvent.RefreshingIndexFinished, () => {
    setTimeout(() => (refreshingIndex.value = false), 500); // artifical delay for transition purposes
    search(currentQuery.value);
  });
});

// utils
function convertFileSrc(protocol: string, filePath: string): string {
  const path = encodeURIComponent(filePath);
  return navigator.userAgent.includes("Windows")
    ? `http://${protocol}.localhost/${path}`
    : `${protocol}://${path}`;
}

function getIconHtml(icon: Icon): string {
  switch (icon.type) {
    case IconType.Default:
    case IconType.Path:
      return `<img src="${convertFileSrc("kalasset", icon.data)}" />`;
    case IconType.Svg:
      return icon.data;
    default:
      return "<span>TODO: empty icon</span>";
  }
}
</script>

<template>
  <main>
    <div
      id="search-input_container"
      :style="{
        'border-radius': results.length === 0 ? '10px 10px' : '10px 10px 0 0',
      }"
    >
      <div id="search-input_icon-container">
        <SearchIcon id="search-input_icon" />
      </div>

      <input
        id="search-input"
        placeholder="Search..."
        v-model="currentQuery"
        @keydown="onkeydown"
      />

      <Transition name="slide-fade">
        <div v-if="refreshingIndex" id="refreshing_icon-container">
          <RefreshingIcon id="refreshing_icon" />
        </div>
      </Transition>
    </div>

    <div id="search-results_container">
      <ul>
        <li
          v-for="(item, index) in results"
          :id="`search-results_item_#${index}`"
          class="search-results_item"
          :class="{ selected: index === currentSelection }"
        >
          <div
            class="search-results_item_left"
            v-html="getIconHtml(item.icon)"
          ></div>
          <div class="search-results_item_right">
            <span class="text-primary">{{ item.primary_text }}</span>
            <span class="text-secondary">{{ item.secondary_text }}</span>
          </div>
        </li>
      </ul>
    </div>
  </main>
</template>

<style>
:root {
  --primary: rgba(21, 20, 20, 0.75);
  --accent: rgba(70, 140, 210, 0.5);
  --accent-lighter: rgba(90, 163, 235, 0.5);
  --text-primary: rgba(180, 180, 180);
  --text-secondary: rgb(100, 100, 100);
  --text-primary-on-accent: rgba(255, 255, 255);
  --text-secondary-on-accent: rgb(160, 160, 160);
}

main {
  overflow: hidden;
  width: 100vw;
  height: 100vh;
}

#search-input_container {
  appearance: none;
  background-color: var(--primary);
  width: 100%;
  height: 60px;
  display: flex;
}

#search-input {
  flex-grow: 1;
  background: transparent;
  height: 100%;
  outline: none;
  border: none;
  font-size: larger;
  color: var(--text-primary);
  padding: 1rem;
}

#search-input::placeholder {
  color: var(--text-secondary);
}

#search-input_icon-container,
#refreshing_icon-container {
  display: grid;
  place-items: center;
  height: 100%;
  width: 50px;
  color: var(--text-primary);
}

.slide-fade-leave-active,
.slide-fade-enter-active {
  transition: all 0.3s ease-out;
}

.slide-fade-enter-from,
.slide-fade-leave-to {
  transform: translateX(20px);
  opacity: 0;
}

#refreshing_icon {
  animation: rotation 1s infinite linear;
}

@keyframes rotation {
  from {
    transform: rotate(0deg);
  }

  to {
    transform: rotate(359deg);
  }
}

#search-results_container {
  overflow-x: hidden;
  background-color: var(--primary);
  width: 100%;
  height: 400px;
  border-radius: 0 0 10px 10px;
}

.search-results_item {
  overflow: hidden;
  padding: 0 10px;
  list-style: none;
  display: flex;
  width: 100%;
  height: 60px;
}

.search-results_item:hover,
.search-results_item.selected {
  background-color: var(--accent);
}

.search-results_item_left {
  flex-shrink: 0;
  width: 60px;
  height: 100%;
  display: grid;
  place-items: center;
}

.search-results_item_left > * {
  width: 50%;
  height: 50%;
}

.search-results_item_right {
  overflow: hidden;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
}

.search-results_item_right span {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}

.text-primary {
  color: var(--text-primary);
}

.text-secondary {
  color: var(--text-secondary);
}

.search-results_item.selected .text-primary {
  color: var(--text-primary-on-accent);
}

.search-results_item.selected .text-secondary {
  color: var(--text-secondary-on-accent);
}
</style>

// src/ui/windows/main.tsx
import { Component, createSignal, For, onMount } from "solid-js";
import { IconType, IPCEvent, SearchResultItem } from "../../common_types";

const MainWindow: Component = () => {
  const [currentSelection, setCurrentSelection] = createSignal(0);
  const [results, setResults] = createSignal<SearchResultItem[]>([]);
  const [refreshingIndex, setRefreshingIndex] = createSignal<boolean>(false);

  function search(query: string) {
    if (query) {
      window.KAL.ipc.send(IPCEvent.Search, query);
    } else {
      setResults([]);
      window.KAL.ipc.send(IPCEvent.ClearResults);
    }
  }

  function onkeydown(e: KeyboardEvent) {
    if (e.key === "Escape") {
      e.preventDefault();
      window.KAL.ipc.send(IPCEvent.HideMainWindow);
    }

    if (["ArrowDown", "ArrowUp"].includes(e.key)) {
      e.preventDefault();
      if (e.key === "ArrowDown") {
        setCurrentSelection(
          currentSelection() === results().length - 1
            ? 0
            : currentSelection() + 1
        );
      } else {
        setCurrentSelection(
          currentSelection() === 0
            ? results().length - 1
            : currentSelection() - 1
        );
      }

      document
        .getElementById(`search-results_item_#${currentSelection()}`)
        .scrollIntoView({ behavior: "smooth", block: "nearest" });
    }

    if (e.key === "Enter") {
      e.preventDefault();
      window.KAL.ipc.send(IPCEvent.Execute, currentSelection(), e.shiftKey);
    }

    if (e.key === "o" && e.ctrlKey) {
      e.preventDefault();
      window.KAL.ipc.send(IPCEvent.OpenLocation, currentSelection());
    }

    if (e.key === "r" && e.ctrlKey) {
      e.preventDefault();
      window.KAL.ipc.send(IPCEvent.Refresh);
      setRefreshingIndex(true);
    }
  }

  onMount(() => {
    window.KAL.ipc.on(IPCEvent.FocusInput, () => {
      let input = document.getElementById("search-input");
      input.focus();
      (input as HTMLInputElement).select();
    });

    window.KAL.ipc.on(IPCEvent.Results, (payload: SearchResultItem[]) => {
      setCurrentSelection(0);
      setResults(payload);
    });

    window.KAL.ipc.on(IPCEvent.RefreshingIndexFinished, () => {
      setRefreshingIndex(false);
    });
  });

  return (
    <main>
      <div id="search-input_container">
        <div id="search-input_icon-container">
          <SearchIcon id="search-input_icon" />
        </div>
        <input
          id="search-input"
          placeholder="Search..."
          onkeydown={(e) => onkeydown(e)}
          onInput={(e) => search(e.currentTarget.value)}
        />
        <div id="refreshing_icon-container">
          <RefreshingIcon id="refreshing_icon" />
        </div>
      </div>

      <div id="search-results_container">
        <ul>
          <For each={results()}>
            {(result, index) => (
              <li
                id={`search-results_item_#${index()}`}
                class="search-results_item"
                classList={{ selected: index() == currentSelection() }}
              >
                <div
                  class="search-results_item_left"
                  innerHTML={
                    result.icon.type === IconType.Svg
                      ? result.icon.data
                      : result.icon.type === IconType.Path
                      ? `<img src="${convertFileSrc(
                          "kalasset",
                          result.icon.data
                        )}" >`
                      : //  TODO: use a default icon
                        ""
                  }
                ></div>
                <div class="search-results_item_right">
                  <span class="text-primary">{result.primary_text}</span>
                  <span class="text-secondary">{result.secondary_text}</span>
                </div>
              </li>
            )}
          </For>
        </ul>
      </div>

      <style jsx dynamic>
        {`
          :root {
            --primary: rgba(31, 31, 31, 0.8);
            --accent: rgba(72, 141, 210, 0.5);
            --text-primary: rgba(255, 255, 255);
            --text-secondary: rgb(107, 107, 107);
          }

          main {
            overflow: hidden;
            width: 100vw;
            height: 100vh;
          }

          #search-input_container {
            appearance: none;
            background-color: var(--primary);
            width: 100%;
            height: 60px;
            border-radius: 10px 10px
              ${results().length === 0 ? "10px 10px" : "0 0"};
            display: flex;
          }

          #search-input {
            flex-grow: 1;
            background: transparent;
            height: 100%;
            outline: none;
            border: none;
            font-size: larger;
            color: var(--text-primary);
            padding: 1rem;
          }

          #search-input::placeholder {
            color: var(--text-secondary);
          }

          #search-input_icon-container,
          #refreshing_icon-container {
            display: grid;
            place-items: center;
            height: 100%;
            width: 50px;
            color: var(--text-primary);
          }

          #refreshing_icon-container {
            opacity: ${refreshingIndex() ? "1" : "0"};
            transition: opacity 1s;
          }

          #refreshing_icon {
            animation: ${refreshingIndex()
              ? "rotation 1s infinite linear"
              : "unset"};
          }

          @keyframes rotation {
            from {
              transform: rotate(0deg);
            }
            to {
              transform: rotate(359deg);
            }
          }

          #search-results_container {
            overflow-x: hidden;
            background-color: var(--primary);
            width: 100%;
            height: 400px;
            border-radius: 0 0 10px 10px;
          }

          .search-results_item {
            overflow: hidden;
            padding: 0 10px;
            list-style: none;
            display: flex;
            width: 100%;
            height: 60px;
          }

          .search-results_item:hover,
          .search-results_item.selected {
            background-color: var(--accent);
          }

          .search-results_item_left {
            flex-shrink: 0;
            width: 60px;
            height: 100%;
            display: grid;
            place-items: center;
          }

          .search-results_item_left > * {
            width: 50%;
            height: 50%;
          }

          .search-results_item_right {
            overflow: hidden;
            height: 100%;
            display: flex;
            flex-direction: column;
            justify-content: center;
          }

          .search-results_item_right span {
            overflow: hidden;
            white-space: nowrap;
            text-overflow: ellipsis;
          }

          .text-primary {
            color: var(--text-primary);
          }

          .text-secondary {
            color: var(--text-secondary);
          }
        `}
      </style>
    </main>
  );
};

export default MainWindow;

function convertFileSrc(protocol: string, filePath: string): string {
  const path = encodeURIComponent(filePath);
  return navigator.userAgent.includes("Windows")
    ? `https://${protocol}.localhost/${path}`
    : `${protocol}://${path}`;
}

const SearchIcon: Component<{ id: string }> = (props) => (
  <svg id={props.id} width="32px" height="32px" viewBox="0 0 24 24">
    <g
      fill="none"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="2"
    >
      <circle cx="10" cy="10" r="7"></circle>
      <path d="m21 21l-6-6"></path>
    </g>
  </svg>
);

const RefreshingIcon: Component<{ id: string }> = (props) => (
  <svg
    id={props.id}
    width="32"
    height="32"
    preserveAspectRatio="xMidYMid meet"
    viewBox="0 0 24 24"
  >
    <path
      fill="none"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="2"
      d="M4 4v5h.582m15.356 2A8.001 8.001 0 0 0 4.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 0 1-15.357-2m15.357 2H15"
    ></path>
  </svg>
);
